"""
Utility to patch the PyTorch satellite notebook with robust path detection.
"""
import json

notebook_path = r"d:\BOOM BAAM\pytorch_satellite_notebook.ipynb"
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 1: Global Imports update
nb['cells'][1]['source'] = [
    "import os\n",
    "import pandas as pd\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from torchvision import transforms, models\n",
    "from PIL import Image\n",
    "from tqdm import tqdm\n",
    "from sklearn.metrics import f1_score, accuracy_score\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import glob\n",
    "\n",
    "# --- SMART CONFIGURATION ---\n",
    "def find_base_path():\n",
    "    kaggle_paths = glob.glob('/kaggle/input/**/Train.csv', recursive=True)\n",
    "    if kaggle_paths: return os.path.dirname(kaggle_paths[0])\n",
    "    local_paths = glob.glob('./**/Train.csv', recursive=True)\n",
    "    if local_paths: return os.path.dirname(local_paths[0])\n",
    "    return \"./main_dataset/DATASET\"\n",
    "\n",
    "BASE_PATH = find_base_path()\n",
    "IMG_SIZE = 224\n",
    "BATCH_SIZE = 48\n",
    "EPOCHS = 20 \n",
    "LEARNING_RATE = 1e-3\n",
    "NUM_CLASSES = 10\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "\n",
    "print(f\"🚀 Device: {DEVICE} | Detected Path: {BASE_PATH}\")"
]

# Cell 7: Training Logic update (Robust Pathing)
nb['cells'][7]['source'] = [
    "# Load data and prepare split\n",
    "train_df_full = pd.read_csv(os.path.join(BASE_PATH, 'Train.csv'))\n",
    "unique_labels = sorted(train_df_full['LABEL'].unique())\n",
    "label_map = {name: i for i, name in enumerate(unique_labels)}\n",
    "inv_label_map = {i: name for name, i in label_map.items()}\n",
    "print(f\"✅ Mapping: {label_map}\")\n",
    "\n",
    "train_data, val_data = train_test_split(\n",
    "    train_df_full, test_size=0.15, stratify=train_df_full['LABEL'], random_state=42\n",
    ")\n",
    "\n",
    "# Detect image directory casing\n",
    "train_img_dir = 'train_images' if os.path.exists(\n",
    "    os.path.join(BASE_PATH, 'train_images')\n",
    ") else 'Train_Images'\n",
    "\n",
    "train_ds = ImageDataset(\n",
    "    train_data, os.path.join(BASE_PATH, train_img_dir), \n",
    "    transform=train_transform, label_map=label_map\n",
    ")\n",
    "val_ds = ImageDataset(\n",
    "    val_data, os.path.join(BASE_PATH, train_img_dir), \n",
    "    transform=val_transform, label_map=label_map\n",
    ")\n",
    "\n",
    "train_loader = DataLoader(\n",
    "    train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=4, pin_memory=True\n",
    ")\n",
    "val_loader = DataLoader(\n",
    "    val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True\n",
    ")\n",
    "\n",
    "# Model build\n",
    "model = models.efficientnet_b0(weights='DEFAULT')\n",
    "model.classifier[1] = nn.Linear(model.classifier[1].in_features, NUM_CLASSES)\n",
    "model = model.to(DEVICE)\n",
    "\n",
    "optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-3)\n",
    "scheduler = optim.lr_scheduler.OneCycleLR(\n",
    "    optimizer, max_lr=LEARNING_RATE, \n",
    "    steps_per_epoch=len(train_loader), epochs=EPOCHS\n",
    ")\n",
    "criterion = nn.CrossEntropyLoss(label_smoothing=0.1)\n",
    "scaler = torch.cuda.amp.GradScaler()\n",
    "\n",
    "best_f1 = 0.0\n",
    "for epoch in range(EPOCHS):\n",
    "    model.train()\n",
    "    train_correct, train_total = 0, 0\n",
    "    pbar = tqdm(train_loader, desc=f\"Epoch {epoch+1}/{EPOCHS}\")\n",
    "    for images, labels in pbar:\n",
    "        images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
    "        optimizer.zero_grad()\n",
    "        with torch.cuda.amp.autocast():\n",
    "            outputs = model(images)\n",
    "            loss = criterion(outputs, labels)\n",
    "        scaler.scale(loss).backward()\n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "        scheduler.step()\n",
    "        \n",
    "        _, predicted = torch.max(outputs.data, 1)\n",
    "        train_total += labels.size(0)\n",
    "        train_correct += (predicted == labels).sum().item()\n",
    "        pbar.set_postfix({'acc': f\"{100*train_correct/train_total:.2f}%\"})\n",
    "\n",
    "    model.eval()\n",
    "    all_preds, all_labels = [], []\n",
    "    with torch.no_grad():\n",
    "        for images, labels in val_loader:\n",
    "            outputs = model(images.to(DEVICE))\n",
    "            _, predicted = torch.max(outputs.data, 1)\n",
    "            all_preds.extend(predicted.cpu().numpy())\n",
    "            all_labels.extend(labels.numpy())\n",
    "            \n",
    "    val_acc = accuracy_score(all_labels, all_preds) * 100\n",
    "    val_f1 = f1_score(all_labels, all_preds, average='macro') * 100\n",
    "    print(f\"⭐ Validation Acc: {val_acc:.2f}% | F1: {val_f1:.2f}%\")\n",
    "    \n",
    "    if val_f1 > best_f1:\n",
    "        best_f1 = val_f1\n",
    "        torch.save(\n",
        "    {'model': model.state_dict(), 'inv_map': inv_label_map}, 'best_model.pth'\n",
        ")\n",
    "        print(\"🔥 New Best Model Saved!\")"
]

# Cell 9: Inference cell (FINAL.csv integer mapping)
nb['cells'][9]['source'] = [
    "print(\"🏁 Generating FINAL.csv for Web Platform...\")\n",
    "checkpoint = torch.load('best_model.pth')\n",
    "model.load_state_dict(checkpoint['model'])\n",
    "model.eval()\n",
    "\n",
    "test_df = pd.read_csv(os.path.join(BASE_PATH, 'Test.csv'))\n",
    "test_img_dir = 'test_images' if os.path.exists(\n",
    "    os.path.join(BASE_PATH, 'test_images')\n",
    ") else 'Test_Images'\n",
    "test_ds = ImageDataset(\n",
    "    test_df, os.path.join(BASE_PATH, test_img_dir), val_transform, is_test=True\n",
    ")\n",
    "test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
    "\n",
    "preds = []\n",
    "with torch.no_grad():\n",
    "    for images in tqdm(test_loader, desc=\"Inference\"):\n",
    "        outputs = model(images.to(DEVICE))\n",
    "        _, p = torch.max(outputs, 1)\n",
    "        preds.extend(p.cpu().numpy())\n",
    "\n",
    "pd.DataFrame(\n",
    "    {'IMAGE': test_df['IMAGE'], 'LABEL': preds}\n",
    ").to_csv('FINAL.csv', index=False)\n",
    "print(f\"✅ DONE! Created FINAL.csv with Integer Labels.\")"
]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("Main notebook updated with Smart Path Detection and FINAL.csv logic.")
