# pylint: disable=duplicate-code
"""
Utility to patch the PyTorch satellite notebook with F1 scoring logic.
"""
import json

notebook_path = r"d:\BOOM BAAM\pytorch_satellite_notebook.ipynb"
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 1: Imports & Config
nb['cells'][1]['source'] = [
    "import os\n",
    "import pandas as pd\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from torchvision import transforms, models\n",
    "from PIL import Image\n",
    "from tqdm import tqdm\n",
    "from sklearn.metrics import f1_score, accuracy_score\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "IMG_SIZE = 224\n",
    "BATCH_SIZE = 32\n",
    "EPOCHS = 20 \n",
    "LEARNING_RATE = 1e-3\n",
    "NUM_CLASSES = 10\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "\n",
    "BASE_PATH = \"./main_dataset/DATASET\"\n",
    "\n",
    "print(f\"🚀 Device: {DEVICE} | Path: {BASE_PATH}\")"
]

# Cell 3: ImageDataset
nb['cells'][3]['source'] = [
    "class ImageDataset(Dataset):\n",
    "    def __init__(self, df, root_dir, transform=None, is_test=False, label_map=None):\n",
    "        self.df = df\n",
    "        self.root_dir = root_dir\n",
    "        self.transform = transform\n",
    "        self.is_test = is_test\n",
    "        self.label_map = label_map\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        # DATASET/Train.csv uses IMAGE column at index 0\n",
    "        img_name = self.df.iloc[idx, 0]\n",
    "        img_path = os.path.join(self.root_dir, img_name)\n",
    "        try:\n",
    "            image = Image.open(img_path).convert('RGB')\n",
    "        except:\n",
    "            image = Image.new('RGB', (IMG_SIZE, IMG_SIZE))\n",
    "        if self.transform: image = self.transform(image)\n",
    "        if self.is_test: return image\n",
    "        \n",
    "        # DATASET/Train.csv uses LABEL column at index 1\n",
    "        label_name = self.df.iloc[idx, 1]\n",
    "        label = self.label_map[label_name] if self.label_map else int(label_name)\n",
    "        return image, label"
]

# Cell 7: Training Loop
nb['cells'][7]['source'] = [
    "# Load data and prepare split\n",
    "train_df_full = pd.read_csv(os.path.join(BASE_PATH, 'Train.csv'))\n",
    "unique_labels = sorted(train_df_full['LABEL'].unique())\n",
    "label_map = {name: i for i, name in enumerate(unique_labels)}\n",
    "inv_label_map = {i: name for name, i in label_map.items()}\n",
    "print(f\"✅ Mapping: {label_map}\")\n",
    "\n",
    "train_data, val_data = train_test_split(\n",
    "    train_df_full, test_size=0.15, stratify=train_df_full['LABEL'], random_state=42\n",
    ")\n",
    "\n",
    "train_ds = ImageDataset(\n",
    "    train_data, os.path.join(BASE_PATH, 'train_images'), \n",
    "    transform=train_transform, label_map=label_map\n",
    ")\n",
    "val_ds = ImageDataset(\n",
    "    val_data, os.path.join(BASE_PATH, 'train_images'), \n",
    "    transform=val_transform, label_map=label_map\n",
    ")\n",
    "\n",
    "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)\n",
    "val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)\n",
    "\n",
    "# Model build\n",
    "model = models.efficientnet_b0(weights='DEFAULT')\n",
    "model.classifier[1] = nn.Linear(model.classifier[1].in_features, NUM_CLASSES)\n",
    "model = model.to(DEVICE)\n",
    "\n",
    "optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-3)\n",
    "scheduler = optim.lr_scheduler.OneCycleLR(\n",
    "    optimizer, max_lr=LEARNING_RATE, steps_per_epoch=len(train_loader), epochs=EPOCHS\n",
    ")\n",
    "criterion = nn.CrossEntropyLoss(label_smoothing=0.1)\n",
    "\n",
    "best_f1 = 0.0\n",
    "for epoch in range(EPOCHS):\n",
    "    model.train()\n",
    "    train_loss, train_correct, train_total = 0, 0, 0\n",
    "    pbar = tqdm(train_loader, desc=f\"Epoch {epoch+1}/{EPOCHS}\")\n",
    "    for images, labels in pbar:\n",
    "        images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(images)\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        scheduler.step()\n",
    "        \n",
    "        train_loss += loss.item()\n",
    "        _, predicted = torch.max(outputs.data, 1)\n",
    "        train_total += labels.size(0)\n",
    "        train_correct += (predicted == labels).sum().item()\n",
    "        pbar.set_postfix({\n",
        "    'loss': f\"{train_loss/(pbar.n+1):.4f}\", \n",
        "    'acc': f\"{100*train_correct/train_total:.2f}%\"\n",
        "})\n",
    "\n",
    "    model.eval()\n",
    "    all_preds, all_labels = [], []\n",
    "    with torch.no_grad():\n",
    "        for images, labels in val_loader:\n",
    "            images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
    "            outputs = model(images)\n",
    "            _, predicted = torch.max(outputs.data, 1)\n",
    "            all_preds.extend(predicted.cpu().numpy())\n",
    "            all_labels.extend(labels.cpu().numpy())\n",
    "            \n",
    "    val_acc = accuracy_score(all_labels, all_preds) * 100\n",
    "    val_f1 = f1_score(all_labels, all_preds, average='macro') * 100\n",
    "    print(f\"⭐ Validation Acc: {val_acc:.2f}% | F1: {val_f1:.2f}%\")\n",
    "    \n",
    "    if val_f1 > best_f1:\n",
    "        best_f1 = val_f1\n",
    "        torch.save(\n",
        "    {'model': model.state_dict(), 'inv_map': inv_label_map}, 'best_model.pth'\n",
        ")\n",
    "        print(\"🔥 New Best Model Saved!\")"
]

# Cell 9: Inference
nb['cells'][9]['source'] = [
    "print(\"🏁 Generating FINAL.csv...\")\n",
    "checkpoint = torch.load('best_model.pth')\n",
    "model.load_state_dict(checkpoint['model'])\n",
    "inv_map = checkpoint['inv_map']\n",
    "model.eval()\n",
    "\n",
    "test_csv_df = pd.read_csv(os.path.join(BASE_PATH, 'Test.csv'))\n",
    "test_ds = ImageDataset(\n",
    "    test_csv_df, os.path.join(BASE_PATH, 'test_images'), val_transform, is_test=True\n",
    ")\n",
    "test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
    "\n",
    "predictions = []\n",
    "with torch.no_grad():\n",
    "    for images in tqdm(test_loader, desc=\"Inference\"):\n",
    "        outputs = model(images.to(DEVICE))\n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        predictions.extend(preds.cpu().numpy())\n",
    "\n",
    "string_preds = [inv_map[p] for p in predictions]\n",
    "pd.DataFrame(\n",
    "    {'IMAGE': test_csv_df['IMAGE'], 'LABEL': string_preds}\n",
    ").to_csv('FINAL.csv', index=False)\n",
    "print(f\"✅ DONE! Created FINAL.csv with Best F1: {best_f1:.2f}%\")"
]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("Notebook updated for main_dataset with F1 scoring.")
